[package]
name = "bevy_kira_audio"
version = "0.27.0-rc.1"
authors = ["Niklas Eicker <hello@nikl.me>"]
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Bevy plugin for dynamic audio"
repository = "https://github.com/NiklasEi/bevy_kira_audio"
homepage = "https://github.com/NiklasEi/bevy_kira_audio"
documentation = "https://docs.rs/bevy_kira_audio"
keywords = ["bevy", "gamedev", "audio", "music"]
categories = ["game-development", "multimedia::audio"]
readme = "./README.md"
rust-version = "1.96"

[features]
default = ["ogg"]
flac = ["kira/flac"]
mp3 = ["kira/mp3"]
ogg = ["kira/ogg", "kira/vorbis"]
wav = ["kira/wav", "kira/pcm"]
settings_loader = ["dep:ron", "dep:serde", "kira/serde"]

[dependencies]
bevy_app = "0.20.0-rc.1"
bevy_asset = "0.20.0-rc.1"
bevy_curve = "0.20.0-rc.1"
bevy_ecs = "0.20.0-rc.1"
bevy_log = "0.20.0-rc.1"
bevy_math = "0.20.0-rc.1"
bevy_platform = "0.20.0-rc.1"
bevy_reflect = "0.20.0-rc.1"
bevy_transform = "0.20.0-rc.1"
bevy_utils = "0.20.0-rc.1"
anyhow = "1.0"
uuid = { version = "1", features = ["fast-rng"] }
kira = { version = "0.12.1", default-features = false, features = ["cpal"] }
ron = { version = "0.12", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
parking_lot = "0.12"
thiserror = "2"

[dev-dependencies.bevy]
version = "0.20.0-rc.1"
default-features = false
features = ["2d", "3d", "ui"]

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["ogg"]

[[example]]
name = "custom_channel"
path = "examples/custom_channel.rs"
required-features = ["ogg"]

[[example]]
name = "multiple_channels"
path = "examples/multiple_channels.rs"
required-features = ["ogg"]

[[example]]
name = "status"
path = "examples/status.rs"
required-features = ["ogg"]

[[example]]
name = "settings_loader"
path = "examples/settings_loader.rs"
required-features = ["ogg", "settings_loader"]

[[example]]
name = "stress_test"
path = "examples/stress_test.rs"
required-features = ["ogg"]

[[example]]
name = "settings"
path = "examples/settings.rs"
required-features = ["ogg"]

[[example]]
name = "instance_control"
path = "examples/instance_control.rs"
required-features = ["ogg"]

[[example]]
name = "channel_control"
path = "examples/channel_control.rs"
required-features = ["ogg"]

[[example]]
name = "spatial"
path = "examples/spatial.rs"
required-features = ["ogg"]
